# Generated by Django 5.0.6 on 2024-06-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopWeb', '0002_remove_producto_img_alter_producto_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='subcategoria',
            field=models.CharField(max_length=20),
        ),
    ]
