# Generated by Django 5.0.6 on 2024-07-09 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopWeb', '0003_alter_producto_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_direccion',
            name='nombre_dirreccion',
            field=models.CharField(default='Dirrección de envio', max_length=100),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PedidoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='shopWeb.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopWeb.producto')),
            ],
        ),
    ]
