# Generated by Django 5.0.6 on 2024-07-09 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopWeb', '0004_user_direccion_nombre_dirreccion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_direccion',
            old_name='estado',
            new_name='region',
        ),
    ]
