# Generated by Django 5.0.6 on 2024-06-21 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopWeb', '0004_user_direccion_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
