# Generated by Django 5.0.6 on 2024-07-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopWeb', '0006_suscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='monto_elegido',
            field=models.CharField(choices=[(5000, '5000 pesos'), (10000, '10000 pesos'), (15000, '15000 pesos'), ('otro', 'Otro monto')], default=5000, max_length=10),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
