# Generated by Django 5.0.6 on 2024-07-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopWeb', '0007_suscripcion_monto_elegido_alter_suscripcion_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='monto_elegido',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
