# Generated by Django 5.0.6 on 2024-07-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopWeb', '0008_alter_suscripcion_monto_elegido'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
