# Generated by Django 5.0.6 on 2024-07-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopWeb', '0009_suscripcion_activa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='activa',
            field=models.BooleanField(default=False),
        ),
    ]
