# Generated by Django 5.0.6 on 2024-07-10 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopWeb', '0010_alter_suscripcion_activa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suscripcion',
            name='monto_elegido',
        ),
    ]
