# Generated by Django 5.0.6 on 2024-07-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopWeb', '0011_remove_suscripcion_monto_elegido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id_cupon', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
            ],
        ),
    ]
