# Generated by Django 5.0.6 on 2024-07-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopWeb', '0013_alter_cupon_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupon',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
