# Generated by Django 5.0.6 on 2024-07-13 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopWeb', '0014_cupon_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_entrega',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='pagado',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='total',
        ),
        migrations.RemoveField(
            model_name='pedidoproducto',
            name='id',
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion_envio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopWeb.user_direccion'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado_envio',
            field=models.CharField(choices=[('pagado', 'Pagado'), ('preparacion', 'En Preparación'), ('enviado', 'Enviado'), ('transporte', 'En Transporte'), ('entregado', 'Entregado')], default='pagado', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='total_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedidoproducto',
            name='id_pedido_producto',
            field=models.AutoField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedidoproducto',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pedidoproducto',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopWeb.pedido'),
        ),
    ]
